### ISSUE TITLE
share.sh - gzip: stdin: unexpected end of file

### ISSUE THREAD

**Issue by x0rz** [JusticeRage/freedomfighting#3] opened 2017-02-16 09:14 UTC
I don't know why I get this error while trying to retrieve a test file (on Debian 8 x64):
```
$ ./share.sh -d 7 /tmp/lol superkey
Success! Retrieval command: ./share.sh -r lol "superkey" https://transfer.sh/OXr9D/3162
$ ./share.sh -r lol "superkey" https://transfer.sh/OXr9D/3162
error reading input file

gzip: stdin: unexpected end of file
```

**Comment by JusticeRage** [comment] 2017-02-16 12:56
The error message indicates that both gzip and openssl receive an empty input, which in turn implies that wget or curl didn't generate any output. This is most likely caused by a 404 error on the specified URL.

By default, only one download of the file is allowed by the script (this can be controlled with the `-m` option). Any subsequent downloads will be met with a 404 error. Is it possible that you tried to retrieve the same file twice?

EDIT: confirmed, closing this issue as expected behavior. 🙂

**Closed as completed by JusticeRage** 2017-02-16 12:56 UTC
